### ISSUE TITLE
Unhandled error. DiscordAPIError: Missing Permissions

### ISSUE THREAD

**Issue by honeycrypto** [semuxproject/semux-discord-bot#2]
Maybe this unhandled error appears when bot tries DM user with his deposit address, but discord user has strict privacy rules and doesn't allow to send him direct messages (for non friends?)
```
You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
DiscordAPIError: Missing Permissions
    at item.request.gen.end (node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:79:15)
    at then (node_modules/snekfetch/src/index.js:215:21)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:229:7)
```

**Comment by honeycrypto** [comment]
Wasn't this fixed in 58e39d5? Need to test all functionality with discord account with closed DM
